language: node_js
env: CI=true
sudo: required
node_js:
  - "0.10"
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - sleep 15
before_script:
  - echo "replSet = myReplSetName" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - sleep 20
  - mongo --eval 'rs.initiate()'
  - sleep 15
notifications:
  slack: 'mcchrystalgroup:EIED2QRuvpYDmPZSwmVfnlIg#team-c3-github'
cache:
  directories:
    - node_modules
