language: node_js
env: CI=true
sudo: required
node_js:
  - "0.10"
before_install:
  - curl https://fastdl.mongodb.org/osx/mongodb-osx-x86_64-3.1.9.tgz -O
  - tar -xzvf mongodb-osx-x86_64-3.1.9.tgz
  - mkdir -p mongo/db
  - mkdir -p mongo/log
  - ./mongodb-osx-x86_64-3.1.9/bin/mongod --dbpath=./mongo/db --fork --logpath=./mongo/log/test.log
  - sleep 5
  - echo "replSet = myReplSetName" | sudo tee -a /etc/mongodb.conf
  - sudo service mongodb restart
  - mongo --eval 'rs.initiate()'
cache:
  directories:
    - node_modules
